class customthrow {
    public static void main(String a[]) {
        int n = 10;
        int x = 0;
        throw new ArithmeticException("test custom throw exception");
        /*throw by user handle by the default catch */
    }
}